
#----------------------Deployment for NFS --------------------------
kind: Deployment   
apiVersion: apps/v1  
metadata:              
  name: nfs-server
spec:                
  selector: 
    matchLabels:
      role: nfs-server
  replicas: 1        
  template:
    metadata:
      labels: 
        role: nfs-server
    spec:
      containers:
      - name: nfs-server-container
        image: cpuguy83/nfs-server
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: true
        args:
        # Pass the paths to share to the Docker image
        - /exports
        
--- 
        
#----------------------Service for NFS --------------------------
kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs-server
    
  clusterIP: 10.100.224.55 
     
  ports:
    # Open the ports required by the NFS server
    
    
    # Port 8000 for TCP
    - name: tcp-8000
      port: 8000
      protocol: TCP
      
    # Port 2049 for TCP
    - name: tcp-111
      port: 111
      protocol: TCP 
      
    # Port 111 for UDP
    - name: udp-111
      port: 111
      protocol: UDP
    
    
    # Port 2049 for TCP
    - name: tcp-2049
      port: 2049
      protocol: TCP

    # Port 2049 for UDP
    - name: udp-2049
      port: 2049
      protocol: UDP
      
      
    # Port 40001 for TCP
    - name: tcp-40001
      port: 40001
      protocol: TCP

    # Port 40001 for UDP
    - name: udp-40001
      port: 40001
      protocol: UDP

---
      
#----------------------Deployment for SimulationAutomation RestApplication--------------------------
kind: Deployment    
apiVersion: apps/v1 
metadata:              
  name: simulationautomation-k8s
spec:                
  selector: # Selector field defines how the deployment finds which pods to manage
    matchLabels:
      app: simulationautomation-k8s
  replicas: 1        
  template:
    metadata:
      labels: # used for identifying attributes for the objects such as pods and replication controller
        app: simulationautomation-k8s
    spec:
      containers:
      - name: simulationautomation-k8s
        image: simulationautomation-k8s:1.0
        imagePullPolicy: "IfNotPresent"
        # Mount the NFS volume in the container
        volumeMounts:
        - name: nfs-volume
          mountPath: /usr/Simulation
        ports:
        - containerPort: 8080
       
      volumes:
      - name: nfs-volume
        nfs:
         server: 10.100.224.55
         path: /


        
        
        
        
        
        
        
        
        
        
        