apiVersion: v1
kind: Service
metadata:
  name: simulationautomation-k8s
  labels:
    name: simulationautomation-k8s # needs to match with deployment.yaml
spec:
  ports:
    - nodePort: 30164 
      port: 8080      
      targetPort: 8080  #default springboot port
      protocol: TCP
  selector: #Defines how the deployment finds which pods to manage   
    app: simulationautomation-k8s
  type: NodePort       

